networks:
  default:
    name: mytodo-network
    driver: bridge

services:
  api-gateway:
    build:
      context: ./server/api-gateway
      dockerfile: Dockerfile
    networks:
      - default
    ports:
      - "9000:9000"
    environment:
      - API_GATEWAY_PORT=9000
      - AUTH_SERVICE_URL=http://auth-service:9002
      - TODO_SERVICE_URL=http://todo-service:9001
      - USER_SERVICE_URL=http://user-service:9003
      - ACCESS_TOKEN_SECRET=your-secret-key-here
    depends_on:
      - auth-service
      - todo-service

  auth-service:
    build:
      context: ./server/auth-service
      dockerfile: Dockerfile
    networks:
      - default
    ports:
      - "9002:9002"
    environment:
      - AUTH_SERVICE_PORT=9002
      - MONGODB_URI=mongodb://mongo:27017/auth-service
      - ACCESS_TOKEN_SECRET=your-secret-key-here
      - REFRESH_TOKEN_SECRET=your-refresh-secret-key-here
    depends_on:
      mongo:
        condition: service_healthy

  todo-service:
    build:
      context: ./server/todo-service
      dockerfile: Dockerfile
    networks:
      - default
    ports:
      - "9001:9001"
    environment:
      - TODO_SERVICE_PORT=9001
      - MONGODB_URI=mongodb://mongo:27017/todo-service
    depends_on:
      mongo:
        condition: service_healthy

  user-service:
    build:
      context: ./server/user-service
      dockerfile: Dockerfile
    networks:
      - default
    ports:
      - "9003:9003"
    environment:
      - USER_SERVICE_PORT=9003
      - MONGODB_URI=mongodb://mongo:27017/user-service
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:latest
    networks:
      - default
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    networks:
      - default
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_BACKEND_URL=http://localhost:9000

volumes:
  mongo_data:
    